create type public.presentation_status as enum ('draft', 'published', 'archived');
create type public.slide_type as enum ('normal', 'interactive');
create type public.room_status as enum ('draft', 'ready', 'live', 'paused', 'ended');

create table public.presentations (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, title text not null default 'Untitled presentation', description text, thumbnail_url text, status public.presentation_status not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.slides (id uuid primary key default gen_random_uuid(), presentation_id uuid not null references public.presentations(id) on delete cascade, order_index integer not null check (order_index >= 0), title text not null default 'Untitled slide', type public.slide_type not null default 'normal', background jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(presentation_id, order_index));
create table public.slide_elements (id uuid primary key default gen_random_uuid(), slide_id uuid not null references public.slides(id) on delete cascade, type text not null, x numeric not null, y numeric not null, width numeric not null check (width > 0), height numeric not null check (height > 0), rotation numeric not null default 0, z_index integer not null default 0, properties jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.interactions (id uuid primary key default gen_random_uuid(), slide_id uuid not null references public.slides(id) on delete cascade, type text not null, title text not null, description text, config jsonb not null default '{}'::jsonb, required boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.rooms (id uuid primary key default gen_random_uuid(), presentation_id uuid not null references public.presentations(id) on delete cascade, owner_id uuid not null references auth.users(id) on delete cascade, room_code text not null unique check (room_code ~ '^[A-Z0-9]{6,12}$'), status public.room_status not null default 'draft', started_at timestamptz, ended_at timestamptz, created_at timestamptz not null default now());
create table public.participants (id uuid primary key default gen_random_uuid(), room_id uuid not null references public.rooms(id) on delete cascade, display_name text, session_token_hash text not null unique, joined_at timestamptz not null default now(), last_seen_at timestamptz not null default now());
create table public.responses (id uuid primary key default gen_random_uuid(), room_id uuid not null references public.rooms(id) on delete cascade, interaction_id uuid not null references public.interactions(id) on delete cascade, participant_id uuid not null references public.participants(id) on delete cascade, response jsonb not null, created_at timestamptz not null default now(), unique (interaction_id, participant_id));
create table public.assets (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, presentation_id uuid references public.presentations(id) on delete set null, bucket text not null, object_key text not null unique, file_name text not null, mime_type text not null, size bigint check (size >= 0), created_at timestamptz not null default now());

alter table public.presentations enable row level security; alter table public.slides enable row level security; alter table public.slide_elements enable row level security; alter table public.interactions enable row level security; alter table public.rooms enable row level security; alter table public.assets enable row level security;
create policy "Owners manage presentations" on public.presentations for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "Owners manage slides" on public.slides for all using (exists (select 1 from public.presentations p where p.id = presentation_id and p.owner_id = auth.uid())) with check (exists (select 1 from public.presentations p where p.id = presentation_id and p.owner_id = auth.uid()));
create policy "Owners manage elements" on public.slide_elements for all using (exists (select 1 from public.slides s join public.presentations p on p.id = s.presentation_id where s.id = slide_id and p.owner_id = auth.uid())) with check (exists (select 1 from public.slides s join public.presentations p on p.id = s.presentation_id where s.id = slide_id and p.owner_id = auth.uid()));
create policy "Owners manage interactions" on public.interactions for all using (exists (select 1 from public.slides s join public.presentations p on p.id = s.presentation_id where s.id = slide_id and p.owner_id = auth.uid())) with check (exists (select 1 from public.slides s join public.presentations p on p.id = s.presentation_id where s.id = slide_id and p.owner_id = auth.uid()));
create policy "Owners manage rooms" on public.rooms for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "Owners manage assets" on public.assets for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
